# toml-docs-start lang-main
[it]
    languageName = "Italiano"
    contentDir = "content/it"
    weight = 1
    [it.params.head]
        tagline = "Il Monferrato che non ti aspetti"
    [it.params.feature]
        link = "chi-sono"
        caption = "Chi sono"
    [it.params.footer]
        license = "Quest'opera è distribuita con Licenza Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."
        socialTitle = "Seguimi"
        socialCaption = "Informatico atipico appassionato di viaggi e sport"

[en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2
# toml-docs-end lang-main
# toml-docs-start lang-param
    [en.params.head]
        tagline = "The Monferrato you don't expect"
    [en.params.feature]
        link = "about"
        caption = "About"
    [en.params.footer]
        license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."
        socialTitle = "Follow me"
        socialCaption = "Atypical IT specialist keen on travels and sport"
# toml-docs-end lang-param

