# toml-docs-start lang-main
[it]
    languageName = "Italiano"
    contentDir = "content/it"
    weight = 1
    [it.params.head]
        tagline = "Discovering by walking"
    [it.params.feature]
        link = "chi-sono"
        caption = "Chi sono"
    [it.params.footer]
        license = "Quest'opera è distribuita con Licenza Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)"
        socialTitle = "Seguimi"
        socialCaption = "Esploratore di mondi e assaggiatore di gelati, con una mappa in una mano e un cucchiaio nell'altra, pronto a scoprire nuovi gusti e nuovi orizzonti"

[en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2
# toml-docs-end lang-main
# toml-docs-start lang-param
    [en.params.head]
        tagline = "Discovering by walking"
    [en.params.feature]
        link = "about"
        caption = "About"
    [en.params.footer]
        license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)"
        socialTitle = "Follow me"
        socialCaption = "World explorer and ice cream taster, with a map in one hand and a spoon in the other, ready to discover new tastes and new landscapes"

[de]
    languageName = "Deutsch"
    contentDir = "content/de"
    weight = 3
# toml-docs-end lang-main
# toml-docs-start lang-param
    [de.params.head]
        tagline = "Discovering by walking"
    [de.params.feature]
        link = "über-mich"
        caption = "Über mich"
    [de.params.footer]
        license = "Lizenziert unter Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)"
        socialTitle = "Folge mir"
        socialCaption = "Weltentdecker und Eisverkoster, mit einer Landkarte in der einen und einem Löffel in der anderen Hand, bereit, neue Geschmacksrichtungen und neue Horizonte zu entdecken"
# toml-docs-end lang-param

