name = "Monfit"
license = "MIT"
licenselink = "https://github.com/gethinode/hinode/blob/main/LICENSE"
description = "Un semplice blog dove scoprire nuovi sentieri per vivere il Monferrato in modo diverso."
homepage = "https://monfit.netlify.com"
demosite = "https://monfit.netlify.com"
tags = ["blog", "documentation", "minimal", "modern", "customizable", "search", "bootstrap", "monferrato", "trails", "sentieri", "percorsi", "travels", "viaggi"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "versioned documentation"]
min_version = "0.110.0"

[author]
  name = "Marco Aiolo"
  homepage = "https://github.com/zelix888"